
# shell to this image
#   docker exec -it airflow bash

# you can also view the logs for this container when its running
#   docker logs --tail 50 --follow --timestamps jupyter

version: '3.4'

services:

  dbt:
    image: roundrect/dbt
    #build: ./
    restart: always
#    depends_on:
#      - postgres
#    ports:
#      - 8080:8080
    environment:
      - DBT_PROFILES_DIR=/shared/secret/dbt-profile
    volumes:
      # - ./dags:/usr/local/airflow/dags
      - shared:/shared
      # - dbt:/usr/local/dbt
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    # command: "start-notebook.sh --NotebookApp.port=9999 --NotebookApp.token=''"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3

#  postgres:
#    image: postgres:9.6
#    container_name: postgres
#    environment:
#        - POSTGRES_USER=airflow
#        - POSTGRES_PASSWORD=airflow
#        - POSTGRES_DB=airflow

# volumes
# declare volumes that will be shared amongst services
# Use the recipe below to mount a host folder as a shared volume
# http://blog.code4hire.com/2018/06/define-named-volume-with-host-mount-in-the-docker-compose-file/
volumes:
  shared: # host-mounted directory
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/shared
      o: bind


# keep the container running when
# then you can run a shell like this
# command: tail -F anything
#    command: tail -f /dev/stdout
# command: tail -f /var/log/messages
